eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
            
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true  

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.user: DEBUG        
